version: 2
updates:
  - package-ecosystem: gradle
    directory: /2021
    schedule:
      interval: cron
      cron: "* * 22 * *"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cron: "* * 22 * *"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: cron
      cron: "* * 22 * *"