version: 2
updates:
  - package-ecosystem: gradle
    directory: /2021
    schedule:
      interval: cron
      cron: "0 0 23 * *"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cron: "0 8 23 * *"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: cron
      cron: "0 16 23 * *"